"""empty message

Revision ID: 8c3364e2098
Revises: None
Create Date: 2015-11-08 20:25:55.937599

"""

# revision identifiers, used by Alembic.
revision = '8c3364e2098'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Unicode(length=255), nullable=False),
    sa.Column('todo_title', sa.UnicodeText(), nullable=True),
    sa.Column('start_date', sa.Unicode(length=255), nullable=True),
    sa.Column('end_date', sa.Unicode(length=255), nullable=True),
    sa.Column('status', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    ### end Alembic commands ###
